"""
MDL MOL / SDF Writer — Write molecules in V2000 MOL and SDF formats.

Implements the MDL CT file format specification for V2000 connection tables.
Supports:
- Atom block with 3D coordinates
- Bond block with bond orders and stereo
- Properties block (charges, isotopes)
- SDF data items
"""

from datetime import datetime


def write_mol(molecule, filepath=None):
    """
    Write a molecule in MDL MOL V2000 format.

    Args:
        molecule: Molecule with 3D coordinates
        filepath: Path to write file (if None, returns string)

    Returns:
        MOL file content as string (also writes to file if path given)
    """
    lines = []

    # ── Header Block ──
    # Line 1: Molecule name
    lines.append(molecule.name or "Untitled")
    # Line 2: Program/timestamp/dimensions
    timestamp = datetime.now().strftime("%m%d%y%H%M")
    lines.append(f"  SMILES3D {timestamp}3D")
    # Line 3: Comment
    lines.append(f"  Generated by PyChem molecular viewer")

    # ── Counts Line ──
    num_atoms = len(molecule.atoms)
    num_bonds = len(molecule.bonds)

    # Count atoms with charges and isotopes for properties block
    charged_atoms = [(i, a.formal_charge) for i, a in enumerate(molecule.atoms) 
                     if a.formal_charge is not None and a.formal_charge != 0]
    isotope_atoms = [(i, a.isotope) for i, a in enumerate(molecule.atoms) 
                     if a.isotope is not None and a.isotope > 0]

    # Counts line format: aaabbblllfffcccsssxxxrrrpppiiimmmvvvvvv
    counts = f"{num_atoms:3d}{num_bonds:3d}  0  0  0  0  0  0  0  0999 V2000"
    lines.append(counts)

    # ── Atom Block ──
    for atom in molecule.atoms:
        x = atom.x if atom.x is not None else 0.0
        y = atom.y if atom.y is not None else 0.0
        z = atom.z if atom.z is not None else 0.0

        # MDL charge code mapping
        charge_code = _mdl_charge_code(atom.formal_charge)

        # Symbol padded to 3 chars
        symbol = f"{atom.symbol:<3s}"

        # Format: xxxxx.xxxxyyyyy.yyyyzzzzz.zzzz aaaddcccssshhhbbbvvvHHHrrriiimmmnnneee
        atom_line = (
            f"{x:10.4f}{y:10.4f}{z:10.4f} "
            f"{symbol} 0{charge_code:3d}  0  0  0  0  0  0  0  0  0  0"
        )
        lines.append(atom_line)

    # ── Bond Block ──
    for bond in molecule.bonds:
        a1 = bond.begin_atom_idx + 1  # 1-indexed
        a2 = bond.end_atom_idx + 1

        # Bond type
        bond_type = int(bond.order)
        if bond.is_aromatic:
            bond_type = 4  # Aromatic in MOL file

        # Stereo
        stereo = 0
        if bond.stereo == 1:   # Up
            stereo = 1
        elif bond.stereo == 2:  # Down
            stereo = 6

        bond_line = f"{a1:3d}{a2:3d}{bond_type:3d}{stereo:3d}  0  0  0"
        lines.append(bond_line)

    # ── Properties Block ──
    # Charge property lines
    if charged_atoms:
        # M  CHG  n  aaa vvv aaa vvv ...
        for i in range(0, len(charged_atoms), 8):  # Max 8 per line
            batch = charged_atoms[i:i + 8]
            parts = []
            for atom_idx, charge in batch:
                parts.append(f"{atom_idx + 1:4d}{charge:4d}")
            line = f"M  CHG{len(batch):3d}" + "".join(parts)
            lines.append(line)

    # Isotope property lines
    if isotope_atoms:
        for i in range(0, len(isotope_atoms), 8):
            batch = isotope_atoms[i:i + 8]
            parts = []
            for atom_idx, isotope in batch:
                parts.append(f"{atom_idx + 1:4d}{isotope:4d}")
            line = f"M  ISO{len(batch):3d}" + "".join(parts)
            lines.append(line)

    lines.append("M  END")

    content = "\n".join(lines)

    if filepath:
        with open(filepath, 'w', newline='\n') as f:
            f.write(content)

    return content


def write_sdf(molecule, filepath=None, data_fields=None):
    """
    Write a molecule in SDF format (MOL + data items + $$$$).

    Args:
        molecule: Molecule with 3D coordinates
        filepath: Path to write file
        data_fields: Optional dict of data fields to include

    Returns:
        SDF file content as string
    """
    lines = [write_mol(molecule)]

    # Add data fields
    if data_fields:
        for key, value in data_fields.items():
            lines.append(f"> <{key}>")
            lines.append(str(value))
            lines.append("")

    # Add standard data fields
    lines.append("> <MOLECULAR_FORMULA>")
    lines.append(molecule.molecular_formula())
    lines.append("")

    lines.append("> <MOLECULAR_WEIGHT>")
    lines.append(f"{molecule.molecular_weight():.4f}")
    lines.append("")

    # Add partial charges if computed
    charges = [f"{(a.partial_charge or 0.0):.4f}" for a in molecule.atoms]
    if any(float(c) != 0.0 for c in charges):
        lines.append("> <PARTIAL_CHARGES>")
        lines.append(" ".join(charges))
        lines.append("")

    lines.append("$$$$")

    content = "\n".join(lines)

    if filepath:
        with open(filepath, 'w', newline='\n') as f:
            f.write(content)

    return content


def _mdl_charge_code(formal_charge):
    """Convert formal charge to MDL V2000 charge code."""
    charge_map = {
        3: 1,
        2: 2,
        1: 3,
        0: 0,
        -1: 5,
        -2: 6,
        -3: 7,
    }
    return charge_map.get(formal_charge, 0)
